### ISSUE TITLE
Missing script on main camera in demo rig

### ISSUE THREAD

**Issue by harrison-drift** [JanLoehr/XR-Interaction-Toolkit_Extensions#1]
Just went to give your extensions a play, but there's a missing script on the camera in the demo rig and the teleportation doesnt seem to work.

Would be awesome if there was a demo scene available maybe?

**Comment by JanLoehr** [comment]
You're right. I'll set something up tomorrow

**Comment by JanLoehr** [comment]
Fixed that missing script and added an example scene for teleporting. Thanks for the feedback 🙂

**Comment by harrison-drift** [comment]
Awesome, thank you!
